name: cpp-build
on: [push]

jobs:
  build-ubuntu:
    env:
      projectName: testProj
    name: ${{matrix.config.os}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          os: windows-latest, path: 'build/Debug/${{projectName}}.exe'
        }
        - {
          os: ubuntu-latest, path: 'build/${{projectName}}'
        }

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ..
        # run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build
      - name: ls check
        run: ls
      - name: test-run
        run: ${{matrix.config.path}}
      - uses: actions/upload-artifact@v1
        with:
          name: buildFile_${{runner.os}}
          path: build