name: cpp-build
on: [push]

jobs:
  build-ubuntu:
    name: ${{matrix.config.os}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          os: windows-latest, path: 'build/Debug/testProj.exe'
        }
        - {
          os: ubuntu-latest, path: 'build/testProj'
        }

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: ture
          token: ${{secrets.SECRET_TOKEN}}
      - name: Update Submodules
        run: git submodule update --init
        with:
          token: ${{secrets.SECRET_TOKEN}}
      - name: configure
        run: mkdir build && cd build && cmake ..
        # run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: ls check
        run: ls
      - name: ls stb check
        run: ls stb/
      - uses: actions/upload-artifact@v1
        with:
          name: buildFile_${{runner.os}}
          path: build
      - uses: actions/upload-artifact@v1
        with:
          name: workDir${{runner.os}}
          path: ./