name: cpp-build
on: [push]

jobs:
  build-ubuntu:
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ..
        # run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build
      - name: test-run
        run: cd build && ./testProj
      - uses: actions/upload-artifact@v1
        with:
          name: buildFile
          path: build