name: cpp-build
on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build
      - name: test
        run: cd build && test
  upload-build:
    needs: [build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v1
        with:
          name: buildFile
          path: build