name: cpp-build
on: [push]

jobs:
  build-ubuntu:
    name: ${{matrix.config.os}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
          os: windows-latest, ext: '.exe'
        }
        - {
          os: ubuntu-latest, ext: ''
        }

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ..
        # run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: build
        run: cmake --build build
      - name: test-run
        run: cd build && ./testProj${{runner.ext}}
      - uses: actions/upload-artifact@v1
        with:
          name: buildFile_${{runner.os}}
          path: build