name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  mkdir UP && touch UP/artifact.txt
        # shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: githubactions-upload-artifact
          path: UP
      # - uses: hogehoge
